### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '1-MR1'

### ISSUE THREAD

**Issue by dmd** [harvard-nrg/yaxil#15]
ArcGet.py assumes that a `scan_id` is an integer, but that is apparently not always the case:

```
Traceback (most recent call last):
  File "/cm/shared/anaconda3/bin/ArcGet.py", line 230, in <module>
    main()
  File "/cm/shared/anaconda3/bin/ArcGet.py", line 107, in main
    scan_ids = sorted(download.keys(), key=int)
ValueError: invalid literal for int() with base 10: '1-MR1'
```

And here's how it looks in XNAT:

![image](https://user-images.githubusercontent.com/41439/114930655-44b90a00-9e03-11eb-87ba-271ea4551378.png)

**Comment by dmd** [comment]
I think maybe this is what happens when two scans get merged improperly, and probably I should fix this session.

However, probably also ArcGet shouldn't crash.

On the other hand, I wouldn't have known about the issue if it hadn't crashed...

**Comment by tokeefe** [comment]
Yeah, even though I've never personally encountered a scan ID that isn't numeric, the type for a scan ID (i.e., `xnat:imageScanData/ID`) is `xs:string`. So this really should not have been forced to be an integer.

**Comment by tokeefe** [comment]
Can you give this a spin

`pip install git+https://github.com/harvard-nrg/yaxil.git@main#egg=yaxil`

**Comment by dmd** [comment]
Hmm. Something's not quite right.

Suppose I have a session that looks like this:

![image](https://user-images.githubusercontent.com/41439/115996177-3958a200-a5ac-11eb-9913-ca7c68cd6a1e.png)

Then:

```
ddrucker@ogawa ~ via 🐍 v3.9.4 (yaxtest)
❯ ArcGet.py -l 00048079 --username admin --host https://image-test.mclean.harvard.edu
Enter XNAT passphrase:
INFO:/Users/ddrucker/venvs/yaxtest/bin/ArcGet.py:downloading scans 1-MR1,40
reading response data: done.


ddrucker@ogawa ~ via 🐍 v3.9.4 (yaxtest)
❯ ArcGet.py -l 00048079 --username admin --host https://image-test.mclean.harvard.edu --scans 1
Enter XNAT passphrase:
CRITICAL:/Users/ddrucker/venvs/yaxtest/bin/ArcGet.py:no scans found to download
```

It didn't find scan 1.

**Comment by dmd** [comment]
If I grab the json from the Image Session Scans API I do see all three scans.

**Comment by dmd** [comment]
But `yaxil.scans` returns only two.

**Comment by dmd** [comment]
This appears to be a bug in XNAT. Filed [XNAT-6786](https://issues.xnat.org/browse/XNAT-6786).

**Comment by dmd** [comment]
I think that *your* code is correct, however - and I think it's fine to push as the new version.

**Comment by tokeefe** [comment]
If you navigate to your MR Session page and click View > XML and find 

`<xnat:scan ID="1"`

What's does the `xsi:type` attribute show?

**Comment by dmd** [comment]
Oh, interesting. It's `xsi:type="xnat:scScanData"`.

**Comment by tokeefe** [comment]
So I think the bottom line here is that `yaxil.scans` should have been named something like `yaxil.mrscans` because the only scans it sees 👀 are ones of type `xnat:mrScanData`. 

Problem is, there can be _other_ types of scans under an instance of `xnat:mrSessionData` such as `xnat:srScanData` (Structured Report), `xnat:scScanData` (Secondary Capture), and possibly others. If these descended from `xnat:mrScanData` then things would have just worked.

One possibility would be to have `yaxil.scans` query which types of scans exist (`xsi:type`) on the MR Session and call the appropriate function for each scan type. I started this in the `scans` branch, which you can try out using

`pip install git+https://github.com/harvard-nrg/yaxil.git@scans#egg=yaxil`

**Comment by dmd** [comment]
Well, now that I know what it's doing, I no longer care that it's missing the non-mr ones. :)

**Comment by tokeefe** [comment]
> As long as you don't die on non-int scan names, that's good enough for me.

this should be in `pip install yaxil==0.6.3`
