### ISSUE TITLE
Error in proc_anat: FileNotFoundError

### ISSUE THREAD

**Issue by LeonHWan** [harvard-nrg/yaxil#21]
Hi. I encountered an error when using ArcGet.py (version 0.6.5, dwi branch). It was looking for a *run-1_T1w.json file, but there are only *T1w_e1.json, T1w_e2.json, and so on in the directory. Previously it worked fine when I was using version 0.4.2. 

```
Traceback (most recent call last):
  File "/share/pkg.7/yaxil/0.6.5_dwi_beta/install/bin/ArcGet.py", line 233, in <module>
    main()
  File "/share/pkg.7/yaxil/0.6.5_dwi_beta/install/bin/ArcGet.py", line 88, in main
    bids.bids_from_config(sess, scans_meta, config, args.output_dir)
  File "/share/pkg.7/yaxil/0.6.5_dwi_beta/install/lib/python3.8/site-packages/yaxil/bids/__init__.py", line 50, in bids_from_config
    anat_refs = proc_anat(config, args)
  File "/share/pkg.7/yaxil/0.6.5_dwi_beta/install/lib/python3.8/site-packages/yaxil/bids/__init__.py", line 178, in proc_anat
    with open(sidecar_file) as fo:
FileNotFoundError: [Errno 2] No such file or directory: '/Experiments/sub-1/ses-1/anat/sub-1_ses-1_run-1_T1w.json'
```

Is there any quick fix to this issue?

**Comment by tokeefe** [comment]
Sorry for the lack of response. There have been many improvements to the BIDS exporting capability within ArcGet.py over the last few years. If this is still a problem, please open a new issue.
