### ISSUE TITLE
just hangs forever?

### ISSUE THREAD

**Issue by dmd** [harvard-nrg/yaxil#8]
```
$ ArcGet.py -a imagetest -l E18698170 --debug --scans 1 -o dicoms 
DEBUG:yaxil:returning authentication data from ~/.xnat_auth
DEBUG:yaxil:issuing http request https://image-test.mclean.harvard.edu/data/experiments
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): image-test.mclean.harvard.edu:443
DEBUG:urllib3.connectionpool:https://image-test.mclean.harvard.edu:443 "GET /data/experiments?columns=ID%2Clabel%2Cproject%2Cxnat%3Asubjectassessordata%2Fsubject_id%2Csubject_label%2Cinsert_date&label=E18698170 HTTP/1.1" 200 None
DEBUG:yaxil:issuing http request https://image-test.mclean.harvard.edu/data/experiments
DEBUG:yaxil:query parameters {'xsiType': 'xnat:mrSessionData', 'columns': 'URI,insert_date,operator,insert_user,xnat:mrsessiondata/id,xnat:mrsessiondata/label,xnat:mrsessiondata/project,xnat:mrsessiondata/date,xnat:mrsessiondata/time,xnat:subjectdata/id,subject_label,subject_project,xnat:mrscandata/id,xnat:mrscandata/quality,xnat:mrscandata/series_description,xnat:mrscandata/scanner,xnat:mrscandata/scanner/manufacturer,xnat:mrscandata/scanner/model,xnat:mrscandata/frames,xnat:mrscandata/fieldstrength,xnat:mrscandata/note,xnat:mrscandata/type,xnat:mrscandata/parameters/voxelres/x,xnat:mrscandata/parameters/voxelres/y,xnat:mrscandata/parameters/voxelres/z,xnat:mrscandata/parameters/fov/x,xnat:mrscandata/parameters/fov/y,xnat:mrscandata/parameters/tr,xnat:mrscandata/parameters/te,xnat:mrscandata/parameters/flip,xnat:mrscandata/parameters/sequence,xnat:mrscandata/parameters/imagetype,xnat:mrscandata/parameters/scansequence,xnat:mrscandata/parameters/seqvariant,xnat:mrscandata/parameters/acqtype,xnat:mrscandata/parameters/pixelbandwidth', 'xnat:mrSessionData/ID': 'XNAT_E00004', 'format': 'json'}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): image-test.mclean.harvard.edu:443
DEBUG:urllib3.connectionpool:https://image-test.mclean.harvard.edu:443 "GET /data/experiments?xsiType=xnat%3AmrSessionData&columns=URI%2Cinsert_date%2Coperator%2Cinsert_user%2Cxnat%3Amrsessiondata%2Fid%2Cxnat%3Amrsessiondata%2Flabel%2Cxnat%3Amrsessiondata%2Fproject%2Cxnat%3Amrsessiondata%2Fdate%2Cxnat%3Amrsessiondata%2Ftime%2Cxnat%3Asubjectdata%2Fid%2Csubject_label%2Csubject_project%2Cxnat%3Amrscandata%2Fid%2Cxnat%3Amrscandata%2Fquality%2Cxnat%3Amrscandata%2Fseries_description%2Cxnat%3Amrscandata%2Fscanner%2Cxnat%3Amrscandata%2Fscanner%2Fmanufacturer%2Cxnat%3Amrscandata%2Fscanner%2Fmodel%2Cxnat%3Amrscandata%2Fframes%2Cxnat%3Amrscandata%2Ffieldstrength%2Cxnat%3Amrscandata%2Fnote%2Cxnat%3Amrscandata%2Ftype%2Cxnat%3Amrscandata%2Fparameters%2Fvoxelres%2Fx%2Cxnat%3Amrscandata%2Fparameters%2Fvoxelres%2Fy%2Cxnat%3Amrscandata%2Fparameters%2Fvoxelres%2Fz%2Cxnat%3Amrscandata%2Fparameters%2Ffov%2Fx%2Cxnat%3Amrscandata%2Fparameters%2Ffov%2Fy%2Cxnat%3Amrscandata%2Fparameters%2Ftr%2Cxnat%3Amrscandata%2Fparameters%2Fte%2Cxnat%3Amrscandata%2Fparameters%2Fflip%2Cxnat%3Amrscandata%2Fparameters%2Fsequence%2Cxnat%3Amrscandata%2Fparameters%2Fimagetype%2Cxnat%3Amrscandata%2Fparameters%2Fscansequence%2Cxnat%3Amrscandata%2Fparameters%2Fseqvariant%2Cxnat%3Amrscandata%2Fparameters%2Facqtype%2Cxnat%3Amrscandata%2Fparameters%2Fpixelbandwidth&xnat%3AmrSessionData%2FID=XNAT_E00004&format=json HTTP/1.1" 200 None
```

And then it just hangs there doing nothing (I've tried waiting as much as an hour).

**Comment by tokeefe** [comment]
Hmm. What happens if you use `curl` on that last URL

```
curl -L -u <username> 'https://image-test.mclean.harvard.edu/data/experiments?xsiType=xnat%3AmrSessionData&columns=URI%2Cinsert_date%2Coperator%2Cinsert_user%2Cxnat%3Amrsessiondata%2Fid%2Cxnat%3Amrsessiondata%2Flabel%2Cxnat%3Amrsessiondata%2Fproject%2Cxnat%3Amrsessiondata%2Fdate%2Cxnat%3Amrsessiondata%2Ftime%2Cxnat%3Asubjectdata%2Fid%2Csubject_label%2Csubject_project%2Cxnat%3Amrscandata%2Fid%2Cxnat%3Amrscandata%2Fquality%2Cxnat%3Amrscandata%2Fseries_description%2Cxnat%3Amrscandata%2Fscanner%2Cxnat%3Amrscandata%2Fscanner%2Fmanufacturer%2Cxnat%3Amrscandata%2Fscanner%2Fmodel%2Cxnat%3Amrscandata%2Fframes%2Cxnat%3Amrscandata%2Ffieldstrength%2Cxnat%3Amrscandata%2Fnote%2Cxnat%3Amrscandata%2Ftype%2Cxnat%3Amrscandata%2Fparameters%2Fvoxelres%2Fx%2Cxnat%3Amrscandata%2Fparameters%2Fvoxelres%2Fy%2Cxnat%3Amrscandata%2Fparameters%2Fvoxelres%2Fz%2Cxnat%3Amrscandata%2Fparameters%2Ffov%2Fx%2Cxnat%3Amrscandata%2Fparameters%2Ffov%2Fy%2Cxnat%3Amrscandata%2Fparameters%2Ftr%2Cxnat%3Amrscandata%2Fparameters%2Fte%2Cxnat%3Amrscandata%2Fparameters%2Fflip%2Cxnat%3Amrscandata%2Fparameters%2Fsequence%2Cxnat%3Amrscandata%2Fparameters%2Fimagetype%2Cxnat%3Amrscandata%2Fparameters%2Fscansequence%2Cxnat%3Amrscandata%2Fparameters%2Fseqvariant%2Cxnat%3Amrscandata%2Fparameters%2Facqtype%2Cxnat%3Amrscandata%2Fparameters%2Fpixelbandwidth&xnat%3AmrSessionData%2FID=XNAT_E00004&format=json'
```

Also, just curious if you're configured to use a web proxy (`http_proxy` and `https_proxy`) but not excluding this host (`no_proxy`). Still, I would assume that the proxy would timeout at some point under an hour.

**Comment by dmd** [comment]
It immediately returns with a big-ass json ending in:

    "totalRecords": "36",
    "title": "Matching experiments"
  }
}

**Comment by tokeefe** [comment]
Sorry you're having this issue. Getting a Big Az JSON(TM) is the right behavior. I'm still a little stumped why cURL works, but not requests. Also, waiting over an hour seems odd. I'd assume the webserver would timeout.

YAXIL uses [`requests`](https://docs.python-requests.org/en/master/) to make HTTP requests and I'm reading [here](https://docs.python-requests.org/en/master/user/advanced/#timeouts) that the default timeout is to wait _forever_ basically. I could add an argument to set the request timeout, but that isn't going to solve the issue.

Maybe you can help me dig into this. When you're running `ArcGet.py`, do you see activity on the XNAT server? If you `strace -f` the process, do you see it making slow progress or does it just get stuck on file lock or something like that?

**Comment by dmd** [comment]
Honestly not sure what to strace -- my XNAT is inside Docker (I use https://github.com/NrgXnat/xnat-docker-compose ) so all I see is a single java process running as pid 1, and it never has any activity; doing `strace -fp 1` shows:

````
[pid   189] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid   189] futex(0x7fa762afa728, FUTEX_WAKE_PRIVATE, 1) = 0
[pid   189] futex(0x7fa762afa778, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=499999032} <unfinished ...>
```

(repeated forever for all the different threads)

and I don't see any activity different from that when I run the ArcGet.py.

If I strace ArcGet.py I get:

[strace.txt](https://github.com/harvard-nrg/yaxil/files/6222806/strace.txt)

**Comment by dmd** [comment]
> Also, just curious if you're configured to use a web proxy (`http_proxy` and `https_proxy`) but not excluding this host (`no_proxy`). Still, I would assume that the proxy would timeout at some point under an hour.

And no, I'm not using a proxy.

**Comment by dmd** [comment]
I wrote [this](https://gist.githubusercontent.com/dmd/910a7473e1fd77ff8d2a50ac73358b9f/raw/13e2b3e72f971b10d1f502cb98bf362839c39794/gistfile1.txt) which works fine, but I'd rather have your tool's ability to do the bids stuff and get individual scans etc!

**Comment by dmd** [comment]
By the way, when I C-c it, it is in `yaml.load`:

```
Traceback (most recent call last):
  File "/home/ddrucker/.local/bin/ArcGet.py", line 229, in <module>
    main()
  File "/home/ddrucker/.local/bin/ArcGet.py", line 84, in main
    config = yaml.load(args.config, Loader=yaml.FullLoader)
  File "/cm/shared/anaconda3/lib/python3.8/site-packages/yaml/__init__.py", line 112, in load
    loader = Loader(stream)
  File "/cm/shared/anaconda3/lib/python3.8/site-packages/yaml/loader.py", line 24, in __init__
    Reader.__init__(self, stream)
  File "/cm/shared/anaconda3/lib/python3.8/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/cm/shared/anaconda3/lib/python3.8/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/cm/shared/anaconda3/lib/python3.8/site-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
KeyboardInterrupt
```

**Comment by tokeefe** [comment]
Interesting. What happens if you try to open your `~/.xnat_auth` file (in whatever context `ArcGet.py` is running from)?

**Comment by dmd** [comment]
aaaaaand adding a print statement? it thinks args.config is

```
<_io.TextIOWrapper name='<stdin>' mode='r' encoding='utf-8'>
```

!!

**Comment by dmd** [comment]
Uh....

```
    parser.add_argument('-c', '--config', type=ap.FileType('r'), default=sys.stdin,
        help='BIDS configuration')
```

**Comment by tokeefe** [comment]
Yeah. That would be a problem.

**Comment by dmd** [comment]
Yep, that's the problem. It's sitting there trying to read a bids config from stdin. So you need to fix `parse_args`.

**Comment by tokeefe** [comment]
I'm fixing this now. `argparse.FileType` already understands that `--config -` means "read from stdin" so I'm not sure what compelled me to set this to `default=sys.stdin`.

**Comment by tokeefe** [comment]
Should be fixed

```
pip install yaxil==0.6.1
```
